### SCAN SCRIPT FOR OPCUA ###

#! /bin/bash

source config.sh

if [ ! $TIME_STAMP ]; then
  TIME_STAMP="$(date +"%H%M%S")"
fi

# OPCUA
SCAN_PORT=$OPCUA_SCAN_PORT
NUMBER_OF_IP=$OPCUA_NUMBER_OF_IP
PROTOCOL_NAME=$OPCUA_PROTOCOL_NAME
SCAN_RATE=$OPCUA_SCAN_RATE
TIMEOUT=$OPCUA_TIMEOUT
OUTPUT_FILENAME=${PROTOCOL_NAME}_${TIME_STAMP}_${SCAN_PORT}
SCAN_LIST=$OPCUA_SCAN_IP_LIST
ZMAP_OUTPUT_FIELDS=$DEFAULT_ZMAP_OUTPUT_FIELDS

scan_function

# OPCUA Secured
SCAN_PORT=$OPCUA_SECURE_SCAN_PORT
SCAN_LIST=$OPCUA_SECURE_SCAN_IP_LIST
OUTPUT_FILENAME=${PROTOCOL_NAME}_${TIME_STAMP}_${SCAN_PORT}
scan_function "TLS_ENABLED"
