### SCAN SCRIPT FOR AMQP ###

#! /bin/bash

source config.sh

if [ ! $TIME_STAMP ]; then
  TIME_STAMP="$(date +"%H%M%S")"
fi

# AMQP 
SCAN_PORT=$AMQP_SCAN_PORT
NUMBER_OF_IP=$AMQP_NUMBER_OF_IP
PROTOCOL_NAME=$AMQP_PROTOCOL_NAME
SCAN_RATE=$AMQP_SCAN_RATE
TIMEOUT=$AMQP_TIMEOUT
OUTPUT_FILENAME=${PROTOCOL_NAME}_${TIME_STAMP}_${SCAN_PORT}
SCAN_LIST=$AMQP_SCAN_IP_LIST
ZMAP_OUTPUT_FIELDS=$DEFAULT_ZMAP_OUTPUT_FIELDS

scan_function

# AMQP Secured
SCAN_PORT=$AMQP_SECURE_SCAN_PORT
SCAN_LIST=$AMQP_SECURE_SCAN_IP_LIST
OUTPUT_FILENAME=${PROTOCOL_NAME}_${TIME_STAMP}_${SCAN_PORT}
scan_function "TLS_ENABLED"
