### SCAN SCRIPT FOR XMPP ###

#! /bin/bash

source config.sh

if [ ! $TIME_STAMP ]; then
  TIME_STAMP="$(date +"%H%M%S")"
fi

# XMPP 
SCAN_PORT=$XMPP_SCAN_PORT
NUMBER_OF_IP=$XMPP_NUMBER_OF_IP
PROTOCOL_NAME=$XMPP_PROTOCOL_NAME
SCAN_RATE=$XMPP_SCAN_RATE
TIMEOUT=$XMPP_TIMEOUT
OUTPUT_FILENAME=${PROTOCOL_NAME}_${TIME_STAMP}_${SCAN_PORT}
SCAN_LIST=$XMPP_SCAN_IP_LIST
ZMAP_OUTPUT_FIELDS=$DEFAULT_ZMAP_OUTPUT_FIELDS

scan_function

# XMPP Secured
SCAN_PORT=$XMPP_SECURE_SCAN_PORT
SCAN_LIST=$XMPP_SECURE_SCAN_IP_LIST
OUTPUT_FILENAME=${PROTOCOL_NAME}_${TIME_STAMP}_${SCAN_PORT}
scan_function "TLS_ENABLED"
