### SCAN SCRIPT FOR COAP ###

#! /bin/bash

source config.sh

if [ ! $TIME_STAMP ]; then
  TIME_STAMP="$(date +"%H%M%S")"
fi

# COAP 
SCAN_PORT=$COAP_SCAN_PORT
NUMBER_OF_IP=$COAP_NUMBER_OF_IP
PROTOCOL_NAME=$COAP_PROTOCOL_NAME
SCAN_RATE=$COAP_SCAN_RATE
TIMEOUT=$COAP_TIMEOUT
OUTPUT_FILENAME=${PROTOCOL_NAME}_${TIME_STAMP}_${SCAN_PORT}
SCAN_LIST=$COAP_SCAN_IP_LIST
IPV6_SCAN_CMD_OPTION=$COAP_IPV6_SCAN_CMD_OPTION
PROBE_ARGUMENT="coap_packet.pkt"
ZMAP_OUTPUT_FIELDS="saddr,daddr,sport,dport,ipid,ttl,classification,success,repeat,cooldown,timestamp_str"

scan_function

# COAPS

SCAN_PORT=$COAPS_SCAN_PORT
OUTPUT_FILENAME=${PROTOCOL_NAME}_${TIME_STAMP}_${SCAN_PORT}
SCAN_LIST=$COAPS_SCAN_IP_LIST
PROBE_ARGUMENT="DTLS_Client_Hello.pkt"

scan_function "DTLS_ENABLED"

#EOF