### SCAN SCRIPT FOR TELNET ###

#! /bin/bash

source config.sh

if [ ! $TIME_STAMP ]; then
  TIME_STAMP="$(date +"%H%M%S")"
fi

# TELNET 
SCAN_PORT=$TELNET_SCAN_PORT
NUMBER_OF_IP=$TELNET_NUMBER_OF_IP
PROTOCOL_NAME=$TELNET_PROTOCOL_NAME
SCAN_RATE=$TELNET_SCAN_RATE
TIMEOUT=$TELNET_TIMEOUT
OUTPUT_FILENAME=${PROTOCOL_NAME}_${TIME_STAMP}_${SCAN_PORT}
SCAN_LIST=$TELNET_SCAN_IP_LIST
ZMAP_OUTPUT_FIELDS=$DEFAULT_ZMAP_OUTPUT_FIELDS

scan_function
