### SCAN SCRIPT FOR MQTT ###

#! /bin/bash

source config.sh

if [ ! $TIME_STAMP ]; then
  TIME_STAMP="$(date +"%H%M%S")"
fi

# MQTT 
SCAN_PORT=$MQTT_SCAN_PORT
NUMBER_OF_IP=$MQTT_NUMBER_OF_IP
PROTOCOL_NAME=$MQTT_PROTOCOL_NAME
SCAN_RATE=$MQTT_SCAN_RATE
TIMEOUT=$MQTT_TIMEOUT
OUTPUT_FILENAME=${PROTOCOL_NAME}_${TIME_STAMP}_${SCAN_PORT}
SCAN_LIST=$MQTT_SCAN_IP_LIST
ZMAP_OUTPUT_FIELDS=$DEFAULT_ZMAP_OUTPUT_FIELDS

scan_function

# MQTT Secured
SCAN_PORT=$MQTT_SECURE_SCAN_PORT
SCAN_LIST=$MQTT_SECURE_SCAN_IP_LIST
OUTPUT_FILENAME=${PROTOCOL_NAME}_${TIME_STAMP}_${SCAN_PORT}
scan_function "TLS_ENABLED"
